feat: Add pr issue template & code_of_conduct doc
zeabur/cli pull request #83
Opened 2024-01-30 09:13 UTC by hackerchai

#### Description (required)

This pull request add pr template, issue template, CODE_OF_CONDUCT and CONTRIBUTING docs.

#### Related issues & labels (optional)

- Closes 
- Suggested label: enhancement

2024-01-30 09:15 UTC, pan93412 requested changes

2024-01-30 09:15 UTC, pan93412 commented on CONTRIBUTING.md
> +The scope can be:
```suggestion
The scope, for example, can be:
```

2024-01-30 09:15 UTC, pan93412 commented on commitlint.config.js
We obsolete it since this is annoying. I don't think that this is necessary.

2024-01-30 09:27 UTC, pan93412 approved these changes

2024-01-31 10:22 UTC, yuaanlin approved these changes

2024-01-31 10:22 UTC, merged